version: '2'
services:
  db:
    image: postgres

  app:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/code
    ports:
      - "80:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
