version: '2'

volumes:
  pg_data:
    external: false

services:
  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/code
    ports:
      - "80:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
