# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
