# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-01 18:16
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("listings", "0008_auto_20170601_1806")]

    operations = [
        migrations.AlterModelOptions(
            name="listing", options={"ordering": ["boat__name"]}
        ),
        migrations.RenameField(model_name="listing", old_name="name", new_name="title"),
        migrations.AlterField(
            model_name="listing",
            name="slug",
            field=autoslug.fields.AutoSlugField(editable=False, populate_from="title"),
        ),
    ]
