# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-01 18:20
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20170601_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='review', max_length=100, no_check_for_status=True),
        ),
    ]
