# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20170601_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
