# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("boats", "0002_auto_20170527_0616")]

    operations = [
        migrations.AddField(
            model_name="boat",
            name="location",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        )
    ]
