# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("boats", "0005_auto_20170604_0423")]

    operations = [
        migrations.AlterField(
            model_name="boat",
            name="length",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        )
    ]
