# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("boats", "0006_auto_20170608_1709")]

    operations = [
        migrations.AddField(
            model_name="boat",
            name="bluewater",
            field=models.BooleanField(default=False),
        )
    ]
