# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20170527_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='review',
            field=models.BooleanField(default=False),
        ),
    ]
