# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
