# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-01 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20170527_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='not-interested', max_length=100, no_check_for_status=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='status_note',
            field=models.TextField(blank=True),
        ),
    ]
